on:
  push:
    paths:
      - 'CI/*'
      - '.github/workflows/docker_publish.yml'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir


    strategy:
      matrix:

      # include:
      #   - ubuntu_versions: 16.04
      #     targets: base

       ubuntu_versions : [
          16.04,
          18.04,
          ]
       compiler : [
          gcc,
          clang,
          ]
       hdf5_versions : [
         1.10.4,
       ]
       moab_versions : [
         9c96d17,
         develop,
         master,
       ]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Dockerfile_3_moab
        uses: docker/build-push-action@v2
        with:
          file: CI/all.Dockerfile
          context: .
          target: base
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
          tags: ghcr.io/shimwell/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}

    steps:
      - name: Build and push Dockerfile_3_moab
        uses: docker/build-push-action@v2
        with:
          file: CI/all.Dockerfile
          context: .
          target: external_deps
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
          tags: ghcr.io/shimwell/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}

    steps:
      - name: Build and push Dockerfile_3_moab
        uses: docker/build-push-action@v2
        with:
          file: CI/all.Dockerfile
          context: .
          target: hdf5
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
            HDF5=${{ matrix.hdf5_versions }}
          tags: ghcr.io/shimwell/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}


    steps:
      - name: Build and push Dockerfile_3_moab
        uses: docker/build-push-action@v2
        with:
          file: CI/all.Dockerfile
          context: .
          target: moab
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
            HDF5=${{ matrix.hdf5_versions }}
            MOAB=${{ matrix.moab_versions }}
          tags: ghcr.io/shimwell/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}



      # - name: Build and push Dockerfile_1_housekeeping
      #   uses: docker/build-push-action@v2
      #   with:
      #     file: CI/Dockerfile_1_housekeeping
      #     context: .
      #     push: true
      #     build-args: |
      #       UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
      #     tags: ghcr.io/shimwell/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-housekeeping
      