on:
  push:
    branches: ['gh_actions_and_ghcr_for_docker']  # todo replace with main once we know this is working

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir

    strategy:
      matrix:
       ubuntu_versions : [
          16.04,
          18.04,
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pymoab Docker image
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_0_base
          context: .
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
          tags: ghcr.io/shimwell/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}
          # tags: ghcr.io/svalinn/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}

        # if: success()

    strategy:
      matrix:
       compiler : [
          gcc,
          clang,
          ]
       ubuntu_versions : [
          16.04,
          18.04,
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pymoab Docker image
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_1_external_deps
          context: .
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
          tags: ghcr.io/shimwell/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext
          # tags: ghcr.io/svalinn/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}

    